server.port=16001
spring.application.name=apollo-encrypt

app.id=${spring.application.name}
apollo.bootstrap.enabled=true
apollo.bootstrap.eagerLoad.enabled=true
apollo.bootstrap.namespaces=application

